#!/bin/bash
#PBS -N s_tiles
#PBS -l nodes=3:ppn=6
#PBS -j n
#PBS -l walltime=27:00:00
cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python 2_s_tiles.py -ta /public/home/mfeng/ynsu/mosaic_water/data/JRC_silkroad_1984_2020/JRC_1_1_1998_2020/test/tasks/tasks.shp -i /public/home/mfeng/ynsu/mosaic_water/data/JRC_silkroad_1984_2020/tif_sentinel2020/1_1_sentinel_0.00025.tif -o /public/home/mfeng/ynsu/mosaic_water/data/JRC_silkroad_1984_2020/JRC_1_1_1998_2020/test/data/2_s_tiles/test